# Generated by Django 4.1 on 2022-10-01 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_rename_posts_post_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
