# Generated by Django 4.1 on 2022-10-01 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_post_subtitle_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subtitle',
            field=models.CharField(max_length=100),
        ),
    ]
